apiVersion: v1
kind: Service
metadata:
  name: vllm-cpu
  namespace: llm-serving
  labels:
    app.kubernetes.io/name: vllm-cpu
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: vllm-cpu
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
