apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../baseline-cpu8

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: vllm-cpu
    patch: |-
      - op: replace
        path: /spec/template/metadata/labels/serving-variant
        value: baseline-kv768-cpu8
      - op: replace
        path: /spec/template/spec/containers/0/args/17
        value: "805306368"
